# Generated by Django 4.1.5 on 2023-01-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.TextField()),
                ('Country', models.TextField()),
                ('Item_Type', models.TextField()),
                ('Sales_Channel', models.TextField()),
                ('Order_Priority', models.TextField()),
                ('Order_Date', models.TextField()),
                ('Order_ID', models.IntegerField(null=True)),
                ('Ship_Date', models.TextField()),
                ('Units_Sold', models.IntegerField(null=True)),
                ('Unit_Price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Unit_Cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Total_Revenue', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Total_Cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Total_Profit', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'sales_record',
            },
        ),
    ]
